stages:
  - Static Analysis

flake8:
  stage: Static Analysis
  image: python:3.11-slim
  before_script:
    - python -V
    - python -m pip install flake8
  script:
    - flake8 src | tee flake8_report.txt
  artifacts:
    when: on_failure
    paths:
      - flake8_report.txt
